name: Issue Completeness

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  models: read

jobs:
  analyze:
    name: Vérifie que l'issue est complète
    runs-on: ubuntu-latest
    steps:
      - name: Analyse l'issue avec l'IA
        id: ai-response
        uses: actions/ai-inference@v2
        with:
          # Longueur max de la réponse
          token: ${{ secrets.GITHUB_TOKEN }}
          max-tokens: 1000
          system-prompt: |
            You are a GitHub issue assistant. Your task is to analyze newly opened issues for completeness.
            Provide concise, helpful suggestions, ask clarifying questions and identify any missing information that would help resolve the issue faster.
            Always respond in french with ready-to-use markdown content (no code blocks) that can be posted directly as an issue comment.
            Sign off as AI assistant.
          prompt: |
            La nouvelle issue a été ouverte par ${{ github.event.issue.user.login }}
            Title: ${{ github.event.issue.title }}
            Issue Number: ${{ github.event.issue.number }}
            Body:
            ---
            ${{github.event.issue.body}}
            ---
      - name: Ajoute un commentaire sur l'issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: ${{ steps.ai-response.outputs.response }}
      - name: Ajoute un commentaire en passant par le CLI gh
        env:
          token: ${{secrets.GITHUB_TOKEN}}
          BODY: ${{ steps.ai-response.outputs.response }}
        run: gh issue comment ${{ github.event.issue.number }} --body "$BODY"
          
